const { getDatesAndPhases } = require("../../utils/calendar-utils");
const meetingDb = require("../meeting-database");
const logger = require("../../utils/logger");

// Professional minimalist email templates with blue light theme
const EMAIL_THEME = {
  primaryBlue: "#2563EB",
  lightBlue: "#F0F9FF",
  borderGray: "#E5E7EB",
  darkGray: "#374151",
  softGray: "#6B7280",
};

const AI_DISCLAIMER = `---

This email was generated by Astra, an AI-powered meeting scheduler. Our system analyzes availability, timezones, and priorities to optimize scheduling. For questions or concerns, please contact the meeting organizer directly.`;

class MeetingService {
  // Generate professional HTML email header
  emailHeader() {
    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: ${EMAIL_THEME.darkGray}; background-color: #FFFFFF;">
  <div style="max-width: 600px; margin: 0 auto; padding: 20px;">`;
  }

  emailFooter() {
    return `    <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid ${EMAIL_THEME.borderGray}; font-size: 12px; color: ${EMAIL_THEME.softGray};">
      <p style="margin: 8px 0;">---</p>
      <p style="margin: 8px 0;">This email was generated by <strong>Astra</strong>, an AI-powered meeting scheduler. Our system analyzes participant availability, timezones, and priorities to optimize meeting scheduling. For questions, contact the meeting organizer.</p>
    </div>
  </div>
</body>
</html>`;
  }

  emailSection(title, content) {
    return `    <div style="margin-bottom: 24px;">
      ${title ? `<h2 style="margin: 0 0 12px 0; font-size: 16px; font-weight: 600; color: ${EMAIL_THEME.primaryBlue};">${title}</h2>` : ""}
      <div style="color: ${EMAIL_THEME.darkGray}; font-size: 14px; line-height: 1.6;">
        ${content}
      </div>
    </div>`;
  }

  emailHighlight(text) {
    return `<div style="background-color: ${EMAIL_THEME.lightBlue}; border-left: 4px solid ${EMAIL_THEME.primaryBlue}; padding: 16px; margin: 16px 0; border-radius: 4px;">
      <p style="margin: 0; color: ${EMAIL_THEME.darkGray}; font-size: 14px;">${text}</p>
    </div>`;
  }
  formatAvailableSlots(slots) {
    if (!slots || slots.length === 0) {
      const noSlots = "<p style=\"margin: 0; color: ${EMAIL_THEME.softGray};\">Unfortunately, no available slots were found in the next 3 days. Please check your calendar and try again.</p>";
      return this.emailHeader() + 
        this.emailSection("No Available Slots", noSlots) +
        this.emailFooter();
    }

    let content = "<p style=\"margin: 0 0 16px 0; color: ${EMAIL_THEME.darkGray};\">Select your preferred time slot:</p>";
    content += "<table style=\"width: 100%; border-collapse: collapse; margin: 12px 0;\">";
    
    slots.forEach((slot, index) => {
      const bgColor = index % 2 === 0 ? "#FFFFFF" : EMAIL_THEME.lightBlue;
      content += `<tr style="background-color: ${bgColor}; border-bottom: 1px solid ${EMAIL_THEME.borderGray};">
        <td style="padding: 12px; font-weight: 600; color: ${EMAIL_THEME.primaryBlue}; width: 40px;">${index + 1}</td>
        <td style="padding: 12px; color: ${EMAIL_THEME.darkGray};">
          <strong>${slot.date}</strong> • ${slot.phase}<br>
          <span style="font-size: 13px; color: ${EMAIL_THEME.softGray};">${slot.start_time} – ${slot.end_time}</span>
        </td>
      </tr>`;
    });
    content += "</table>";
    
    content += `<p style="margin: 16px 0 0 0; color: ${EMAIL_THEME.softGray}; font-size: 13px;\">Reply with the option number (e.g., "1" or "Option 2")</p>`;

    return this.emailHeader() + 
      this.emailSection("Available Meeting Slots", content) +
      this.emailFooter();
  }

  async getAvailableSlotsEmail(duration = 60, timezone = "Asia/Kolkata") {
    try {
      logger.info("Fetching available calendar slots");
      const slots = await getDatesAndPhases(duration, timezone);
      return {
        slots,
        message: this.formatAvailableSlots(slots),
      };
    } catch (error) {
      logger.error("Failed to get available slots", error);
      return {
        slots: [],
        message:
          "I encountered an error while checking the calendar. Please try again later.",
      };
    }
  }

  parseSlotSelection(text, availableSlots) {
    if (!availableSlots || availableSlots.length === 0) {
      return null;
    }

    const numberMatch = text.match(/\b(\d+)\b/);
    if (numberMatch) {
      const selectedIndex = parseInt(numberMatch[1]) - 1;
      if (selectedIndex >= 0 && selectedIndex < availableSlots.length) {
        return availableSlots[selectedIndex];
      }
    }

    const optionMatch = text.match(/option\s+(\d+)/i);
    if (optionMatch) {
      const selectedIndex = parseInt(optionMatch[1]) - 1;
      if (selectedIndex >= 0 && selectedIndex < availableSlots.length) {
        return availableSlots[selectedIndex];
      }
    }

    return null;
  }

  extractParticipants(text) {
    const participants = [];
    const lines = text.split("\n");

    for (const line of lines) {
      const emailMatch = line.match(
        /([a-zA-Z0-9._-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+)/
      );
      if (emailMatch) {
        const email = emailMatch[1];
        const nameMatch = line.match(/([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)/);
        const timezoneMatch = line.match(
          /(Asia\/Kolkata|America\/New_York|Europe\/London|UTC[+-]\d+)/i
        );
        const priorityMatch = line.match(/priority[\s:]+(\d+)/i) || line.match(/,\s*(\d+)\s*$/);

        participants.push({
          name: nameMatch ? nameMatch[1] : email.split("@")[0],
          email: email,
          timezone: timezoneMatch ? timezoneMatch[1] : "Asia/Kolkata",
          priority: priorityMatch ? parseInt(priorityMatch[1]) : 0,
        });
      }
    }

    return participants;
  }

  formatAvailabilityRequest(selectedSlot, organizerName) {
    const content = `<p style="margin: 0 0 12px 0;">Hi there,</p>
      <p style="margin: 0 0 16px 0;">${organizerName || 'Your meeting organizer'} has selected a date for an upcoming meeting.</p>
      
      ${this.emailHighlight(`<strong>Date:</strong> ${selectedSlot.date}<br><strong>Preferred Phase:</strong> ${selectedSlot.phase} (morning, afternoon, or evening)`)}
      
      <p style="margin: 16px 0 8px 0; font-weight: 600; color: ${EMAIL_THEME.primaryBlue};">Please Reply With Your Availability</p>
      <p style="margin: 8px 0; color: ${EMAIL_THEME.softGray}; font-size: 13px;">Send your available time window in any of these formats:</p>
      <ul style="margin: 8px 0; padding-left: 20px; color: ${EMAIL_THEME.darkGray}; font-size: 13px;">
        <li>"Available from 09:00 to 11:00"</li>
        <li>"09:00 to 11:00"</li>
        <li>"09:00–11:00"</li>
      </ul>
      
      <p style="margin: 16px 0 0 0; color: ${EMAIL_THEME.softGray}; font-size: 13px;">We'll combine everyone's availability to find the best time.</p>`;

    return this.emailHeader() + 
      this.emailSection("Meeting Date Confirmation", content) +
      this.emailFooter();
  }

  parseAvailabilityResponse(text) {
    // Match formats like:
    // "Available from 09:00 to 11:00"
    // "09:00 to 11:00"
    // "09:00-11:00"
    // "9am to 11am"
    
    const patterns = [
      /(?:from\s+)?(\d{1,2}:\d{2})\s*(?:to|-)\s*(\d{1,2}:\d{2})/i,
      /(\d{1,2})\s*(?:am|pm)\s*(?:to|-)\s*(\d{1,2})\s*(?:am|pm)/i,
    ];

    for (const pattern of patterns) {
      const match = text.match(pattern);
      if (match) {
        return {
          start_time: this.normalizeTime(match[1]),
          end_time: this.normalizeTime(match[2]),
        };
      }
    }

    return null;
  }

  normalizeTime(time) {
    // Convert time to HH:MM format
    if (time.includes(':')) {
      const [h, m] = time.split(':');
      return `${h.padStart(2, '0')}:${m.padStart(2, '0')}`;
    }
    // Handle am/pm format
    return time;
  }

  formatMeetingInvite(selectedSlot, organizerName, participants) {
    let invite = `Meeting Confirmation\n\n`;
    invite += `The meeting has been scheduled for:\n`;
    invite += `Date: ${selectedSlot.date}\n`;
    invite += `Time: ${selectedSlot.start_time} - ${selectedSlot.end_time} (${selectedSlot.phase})\n\n`;

    if (organizerName) {
      invite += `Organizer: ${organizerName}\n`;
    }

    if (participants && participants.length > 0) {
      invite += `\nParticipants:\n`;
      participants.forEach((p) => {
        const availText = p.availability_start && p.availability_end 
          ? ` (Available: ${p.availability_start} - ${p.availability_end})`
          : '';
        invite += `- ${p.name} (${p.email}) - ${p.timezone} - Priority: ${p.priority || 0}${availText}\n`;
      });
    }

    invite += `\nLooking forward to seeing you there!`;

    return invite;
  }

  printParticipantData(participants, selectedSlot) {
    console.log(`\n${"=".repeat(70)}`);
    console.log(`ALL PARTICIPANTS HAVE RESPONDED - MEETING DATA`);
    console.log(`${"=".repeat(70)}`);
    console.log(`\nSelected Date: ${selectedSlot.date}`);
    console.log(`Selected Phase: ${selectedSlot.phase}\n`);
    console.log(`Participants Data:`);
    console.log(`${"-".repeat(70)}`);
    
    participants.forEach((p, idx) => {
      console.log(`\n${idx + 1}. ${p.name}`);
      console.log(`   Email: ${p.email}`);
      console.log(`   Timezone: ${p.timezone}`);
      console.log(`   Priority: ${p.priority || 0}`);
      console.log(`   Availability: ${p.availability_start || 'N/A'} - ${p.availability_end || 'N/A'}`);
      console.log(`   Responded: ${p.has_responded ? 'Yes' : 'No'}`);
    });
    
    console.log(`\n${"=".repeat(70)}\n`);
  }

  // Format confirmation email for participants
  formatParticipantConfirmation(participant, selectedSlot, meetLink, calendarLink, meetingTitle) {
    const { DateTime } = require('luxon');
    
    const slotTime = DateTime.fromISO(`${selectedSlot.date}T${selectedSlot.start_time}`, { zone: 'UTC' });
    const localTime = slotTime.setZone(participant.timezone);
    const endTime = localTime.plus({ hours: 1 });
    
    let content = `<p style="margin: 0 0 16px 0;">Hi ${participant.name},</p>
      <p style="margin: 0 0 16px 0;">Your meeting has been scheduled!</p>
      
      ${this.emailHighlight(`<strong>${meetingTitle}</strong><br><strong>${selectedSlot.date}</strong> at <strong>${localTime.toFormat('HH:mm')} – ${endTime.toFormat('HH:mm')}</strong><br><span style="font-size: 13px;">${participant.timezone}</span>`)}
      
      <div style="margin: 20px 0;">
        ${meetLink ? `<div style="margin-bottom: 12px;"><a href="${meetLink}" style="display: inline-block; background-color: ${EMAIL_THEME.primaryBlue}; color: white; padding: 10px 16px; text-decoration: none; border-radius: 4px; font-weight: 500; font-size: 14px;">Join Meeting</a></div>` : ''}
        ${calendarLink ? `<div><a href="${calendarLink}" style="color: ${EMAIL_THEME.primaryBlue}; text-decoration: none; font-size: 13px;">View in Calendar</a></div>` : ''}
      </div>
      
      <p style="margin: 16px 0 0 0; font-size: 13px; color: ${EMAIL_THEME.softGray};">Your availability and timezone preferences were considered in scheduling this time. The meeting has been added to your Google Calendar.</p>`;

    return this.emailHeader() + 
      this.emailSection("Meeting Scheduled", content) +
      this.emailFooter();
  }

  // Format detailed explanation email for organizer
  formatOrganizerExplanation(allSlots, selectedSlot, participants, meetLink, calendarLink, meetingTitle) {
    const { DateTime } = require('luxon');
    
    let content = `<p style="margin: 0 0 16px 0;">Your meeting has been automatically scheduled using optimal time analysis.</p>`;
    
    // Selected slot section
    const slotTime = DateTime.fromISO(`${selectedSlot.date}T${selectedSlot.start_time}`, { zone: 'UTC' });
    const endTime = slotTime.plus({ hours: 1 });
    
    let selectedContent = `<strong>Date:</strong> ${selectedSlot.date}<br><strong>Time:</strong> ${slotTime.toISO()}<br><strong>Score:</strong> ${selectedSlot.score.toFixed(1)} (highest)<br><br>`;
    selectedContent += `<strong>Local Times:</strong><br>`;
    participants.forEach(p => {
      const localTime = slotTime.setZone(p.timezone);
      const localEnd = endTime.setZone(p.timezone);
      selectedContent += `${p.name}: ${localTime.toFormat('HH:mm')} – ${localEnd.toFormat('HH:mm')} (${p.timezone})<br>`;
    });
    
    content += this.emailHighlight(selectedContent);
    
    // Meeting links
    content += `<div style="margin: 20px 0;">`;
    if (meetLink) {
      content += `<div style="margin-bottom: 12px;"><a href="${meetLink}" style="display: inline-block; background-color: ${EMAIL_THEME.primaryBlue}; color: white; padding: 10px 16px; text-decoration: none; border-radius: 4px; font-weight: 500; font-size: 14px;">Join Meeting</a></div>`;
    }
    if (calendarLink) {
      content += `<div><a href="${calendarLink}" style="color: ${EMAIL_THEME.primaryBlue}; text-decoration: none; font-size: 13px;">View in Calendar</a></div>`;
    }
    content += `</div>`;
    
    // Why this slot was chosen
    content += `<p style="margin: 16px 0 8px 0; font-weight: 600; color: ${EMAIL_THEME.primaryBlue}; font-size: 15px;">Why This Time?</p>`;
    content += `<p style="margin: 8px 0; color: ${EMAIL_THEME.darkGray}; font-size: 13px;">This slot scored highest (${selectedSlot.score.toFixed(1)}) by optimizing for:</p>`;
    content += `<ul style="margin: 8px 0; padding-left: 20px; color: ${EMAIL_THEME.darkGray}; font-size: 13px;">
      <li>Participant availability overlap</li>
      <li>Priority weighting (${participants.map(p => `${p.name}: ${p.priority || '–'}`).join(', ')})</li>
      <li>Business hour preferences (9 AM – 5 PM)</li>
      <li>Timezone fairness (reasonable local times)</li>
    </ul>`;
    
    // Other options considered
    if (allSlots.length > 1) {
      content += `<p style="margin: 16px 0 8px 0; font-weight: 600; color: ${EMAIL_THEME.primaryBlue}; font-size: 15px;">Other Options Considered</p>`;
      content += `<table style="width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 13px;">`;
      allSlots.slice(1).forEach((slot, idx) => {
        const otherTime = DateTime.fromISO(`${slot.date}T${slot.start_time}`, { zone: 'UTC' });
        const bgColor = idx % 2 === 0 ? "#FFFFFF" : EMAIL_THEME.lightBlue;
        content += `<tr style="background-color: ${bgColor}; border-bottom: 1px solid ${EMAIL_THEME.borderGray};">
          <td style="padding: 8px; font-weight: 600; color: ${EMAIL_THEME.softGray}; width: 40px;">Option ${idx + 2}</td>
          <td style="padding: 8px; color: ${EMAIL_THEME.darkGray};">Score: ${slot.score.toFixed(1)} • ${participants.map(p => `${p.name}: ${otherTime.setZone(p.timezone).toFormat('HH:mm')}`).join(' • ')}</td>
        </tr>`;
      });
      content += `</table>`;
    }
    
    content += `<p style="margin: 16px 0 0 0; color: ${EMAIL_THEME.softGray}; font-size: 13px;">All participants have been notified and the meeting is on their calendars.</p>`;

    return this.emailHeader() + 
      this.emailSection(`Meeting Scheduled: ${meetingTitle}`, content) +
      this.emailFooter();
  }
}

module.exports = new MeetingService();
